# Generated by Django 3.0.7 on 2021-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='card_id',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
