# Generated by Django 3.0.7 on 2021-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210916_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
