# Generated by Django 3.0.7 on 2021-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='old_price',
            field=models.IntegerField(),
        ),
    ]
